sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 'gem update --system'
  - 'gem install sass --version "=3.4.15"'
  - 'gem install compass --version "=1.0.3"'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'npm install'
after_script:
  - 'cat ./coverage/PhantomJS 1.9.8 (Windows 8 0.0.0)/lcov.info > lcov.info'
  - 'node node_modules/lcov-filter/index.js lcov.info config | ./node_modules/coveralls/bin/coveralls.js && rm -rf coverage'
